### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by Cl1cker0** [ECTO-1A/AppleJuice#26]
![Screenshot_2023-09-12-11-07-30-289_com termux](https://github.com/ECTO-1A/AppleJuice/assets/110249809/d211f9f5-b83f-41c8-b1a4-4f59ee4fb33b)
Traceback (most recent call last):                        File "/home/kali/AppleJuice/app.py", line 144, in <module>                                                        main()                                                File "/home/kali/AppleJuice/app.py", line 113, in main    toggle_device(dev_id, True)                           File "/home/kali/AppleJuice/utils/bluetooth_utils.py", line 88, in toggle_device                                  hci_sock = socket.socket(socket.AF_BLUETOOTH,         File "/usr/local/lib/python3.9/socket.py", line 232, in __init__                                                  _socket.socket.__init__(self, family, type, proto, fileno)                                                  PermissionError: [Errno 13] Permission denied

**Comment by Cl1cker0** [comment]
yet me doing it with sudo still permission error

**Comment by ckcr4lyf** [comment]
Is your phone rooted?

**Comment by mamhadu** [comment]
You need elevated privileges to use sockets. Run it has root.
