### ISSUE TITLE
idk why this is not working im using linux mint cinnamon 

### ISSUE THREAD

**Issue by MrScratchcat** [ECTO-1A/AppleJuice#51]
sudo python3 app.py --random
Advertising Started... Press Ctrl+C to Stop
An error occurred: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Traceback (most recent call last):
  File "/home/mrscratchcat/AppleJuice/app.py", line 132, in main
    start_le_advertising(sock, adv_type=0x03, min_interval=args.interval, max_interval=args.interval, data=bt_data)
  File "/home/mrscratchcat/AppleJuice/utils/bluetooth_utils.py", line 234, in start_le_advertising
    bluez.hci_send_cmd(sock, OGF_LE_CTL, OCF_LE_SET_ADVERTISING_PARAMETERS,
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrscratchcat/AppleJuice/app.py", line 148, in <module>
    main()
  File "/home/mrscratchcat/AppleJuice/app.py", line 145, in main
    stop_le_advertising(sock)
  File "/home/mrscratchcat/AppleJuice/utils/bluetooth_utils.py", line 257, in stop_le_advertising
    bluez.hci_send_cmd(sock, OGF_LE_CTL, OCF_LE_SET_ADVERTISE_ENABLE, cmd_pkt)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by bot910** [comment]
I had the same error on ubuntu 22.04
